# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build & Test
      working-directory: ./EssentialFeed
      run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI" -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO
